MANUAL_SUGGESTIONS = [
    {"title": "Shape of You - Ed Sheeran", "vidid": "JGwWNGJdvx8"},
    {"title": "Tum Hi Ho - Aashiqui 2", "vidid": "IJq0yyWug1k"},
    {"title": "See You Again - Wiz Khalifa", "vidid": "RgKAFK5djSk"},
    {"title": "Kesariya - Brahmastra", "vidid": "BddP6PYo2gs"},
    {"title": "Despacito - Luis Fonsi", "vidid": "kJQP7kiw5Fk"},
    {"title": "Raataan Lambiyan - Shershaah", "vidid": "gvyUuxdRdR4"},
    {"title": "Faded - Alan Walker", "vidid": "60ItHLz5WEA"},
    {"title": "Apna Bana Le - Bhediya", "vidid": "ElZfdU54Cp8"},
    {"title": "Believer - Imagine Dragons", "vidid": "7wtfhZwyrcc"},
    {"title": "Jai Ho - Slumdog Millionaire", "vidid": "xwwAVRyNmgQ"},
    {"title": "Perfect - Ed Sheeran", "vidid": "2Vv-BfVoq4g"},
    {"title": "Kun Faya Kun - Rockstar", "vidid": "T94PHkuydcw"},
    {"title": "Let Me Love You - DJ Snake", "vidid": "euCqAq6BRa4"},
    {"title": "Kabira - Yeh Jawaani Hai Deewani", "vidid": "jHNNMj5bNQw"},
    {"title": "Closer - The Chainsmokers", "vidid": "PT2_F-1esPk"},
    {"title": "Agar Tum Saath Ho - Tamasha", "vidid": "xRb8hxwN5zc"},
    {"title": "Senorita - Shawn Mendes", "vidid": "Pkh8UtuejGw"},
    {"title": "Gerua - Dilwale", "vidid": "AEIVhBS6baE"},
    {"title": "Chaleya - Jawan", "vidid": "VAdGW7QDJiU"},
    {"title": "Vaaste - Dhvani Bhanushali", "vidid": "BBAyRBTfsOU"},
    {"title": "Ishqa Ve (official video)", "vidid": "j18MRhEfmPk"},
    {"title": "Dooron Dooron (official video)", "vidid": "LV_wiOhO40Q"},
    {"title": "Ishq Di Baajiyaan - Diljit", "vidid": "rnyrDk4G68g"},
    {"title": "SUNIYAN SUNIYAN (Official Video)", "vidid": "AKH6ZNSnWOA"},
    {"title": "Shiddat Title Track", "vidid": "iSo9l950QLo"},
    {"title": "KHAAB | AKHIL |", "vidid": "2eliQ_KR8yA"},
    {"title": "Dil Tu Jaan Tu", "vidid": "kyjg5kX4pT0"},
    {"title": "Heeriye", "vidid": "RLzC55ai0eo"},
    {"title": "Sahiba (Music Video)", "vidid": "NW6Dgax2d6I"},
    {"title": "Maan Meri Jaan", "vidid": "VuG7ge_8I2Y"},
    {"title": "Waalian : Harnoor", "vidid": "rCoPr8UwRMc"},
    {"title": "Tu Hai Kahan By - AUR", "vidid": "AX6OrbgS8lI"},
    {"title": "Gehra Hua | Dhurandhar", "vidid": "GX9x62kFsVU"},
    {"title": "Teri Ankhon Mein Song", "vidid": "mClF6mJV5xM"},
    {"title": "Afusic - Pal Pal", "vidid": "8of5w7RgcTc"},
    {"title": "Charlie Puth - We Don't Talk", "vidid": "3AtDnEC4zak"},
    {"title": " Bruno Mars - Die With A Smile", "vidid": "kPa7bsKwL-c"},
    {"title": "Elyanna - I don’t need nobody", "vidid": "Yxjx2YpNTdw"},
    {"title": "Cinnamon Girl", "vidid": "DCYmJDO2_IE"},
    {"title": "Summertime Sadness", "vidid": "TdrL3QxjyVw"},
    {"title": "Djo - End of Beginning", "vidid": "Ec08db2hP10"},
    {"title": "One Direction - Night Changes", "vidid": "syFZfO_wfMQ?si"},
    {"title": "AURORA - Runaway", "vidid": "d_HlPboLRL8"},
    {"title": "Angels For Each Other", "vidid": "OTMQJ656r-M"},
    {"title": "Ed Sheeran - Sapphire ", "vidid": "JgDNFQ2RaLQ"},
    {"title": "Akshath - Nadaaniyan", "vidid": "gPpQNzQP6gE"},
    {"title": "Dhun Song | Saiyaara ", "vidid": "cUmUOb7j3dc"},
    {"title": "Saiyaara Reprise - Female", "vidid": "asG7cwxi1sA"},
    {"title": "Mehabooba Video Song", "vidid": "suk3mW0tDPA"},
    {"title": "Jug Jug Jeeve", "vidid": "Irw8llgSC3s"},
    {"title": "Aashiqui Aa Gayi", "vidid": "lm3yy29vbqM"},
    {"title": "Dil Lutiya | Jazzy B ", "vidid": "TI7RQO2cuh0"},
    {"title": "Why This Kolaveri Di Official ", "vidid": "YR12Z8f1Dh8"},
    {"title": "Agent Vinod Pyar Ki Pungi", "vidid": "Sjh1PQ9B73Y"},
    {"title": "DIL CHEEZ TUJHE DEDI", "vidid": "BkA0lq-0f14"},
    {"title": "Afghan Jalebi (Ya Baba) ", "vidid": "zC3UbTf4qrM"},
    {"title": "Badtameez Dil", "vidid": "II2EO3Nw4m0"},
    {"title": "Gulaabo - Shaandaar", "vidid": "aHSyRPBYTc4"},
    {"title": "Thodi Si Daaru", "vidid": "slM5s55Jz0k"},
    {"title": "Uyi Amma - Azaad", "vidid": "FZLadzn5i6Q"},
    {"title": "Hass Hass - Diljit X Sia", "vidid": "jADTdg-o8i0"},
    {"title": "Barbaadiyan", "vidid": "vJQMhj6WYZA"},
    {"title": "Piya More", "vidid": "F6wn3Cw-o0g"},
    {"title": "Ude Dil Befikre", "vidid": "gXe-KWe-YMs"},
    {"title": "Make Some Noise For Desi Boyz", "vidid": "lyWHtKq1PcQ"},
    {"title": "Sunny Sunny Yaariyan", "vidid": "MXJCnccDLA0"},
    {"title": "Manali Trance | Yo Yo Honey Singh", "vidid": "iytiCRR5yFA"},
    {"title": "DIVINE - Chal Bombay", "vidid": "86B3sXJXSnY"},
  
]
